name: Build and Release mDirt

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build with PyInstaller
      run: |
        pyinstaller src/main.py --name mDirt-${{ github.ref_name }} --icon "assets/icon.ico" --onedir --windowed --add-data "lib;lib" --add-data "assets;assets" --add-data "src;src" --add-data "workspaces;workspaces" --hidden-import=jinja2 --hidden-import=jinja2.ext

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: mDirt-${{ github.ref_name }}
        path: dist/mDirt-${{ github.ref_name }}/

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: mDirt ${{ github.ref_name }}
        files: dist/mDirt-${{ github.ref_name }}/**/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
